"""
检查 Streamlit checkbox 状态管理
这个脚本将帮助我们理解为什么勾选了 checkbox 但还是没有图片
"""

print("=" * 60)
print("Streamlit checkbox 状态管理分析")
print("=" * 60)
print()

print("问题：勾选了'显示证书图片'，但生成的文件中没有图片")
print()

print("可能的原因：")
print("1. checkbox 的 value=False 每次都重新设置")
print("2. 页面重新渲染时，checkbox 又回到了 False")
print("3. session state 中没有保存 checkbox 的值")
print("4. 参数传递链断裂")
print()

print("=" * 60)
print("代码分析：")
print("=" * 60)
print()

print("【问题代码】（之前的版本）：")
print()
print("```python")
print("# 步骤4：生成文件")
print("if current_step >= 3:")
print("    st.markdown('---')")
print("    # 【问题】这里设置了 value=False")
print("    show_cert_images = st.checkbox('显示证书图片', value=False, key='show_cert_images_final',")
print("                                            ^^^^^^^^^^^^")
print("    help='选中后，证书 PDF 会转换为图片...')")
print()
print("    # 【问题】页面重新渲染时，checkbox 又回到了 False")
print("    # 【问题】生成文件按钮在另一个 expander 中")
print("    # 【问题】点击按钮时，可能又触发了重新渲染")
print()
print("    with st.expander('📝 步骤4：生成投标文件', expanded=(current_step == 3)):")
print("        st.info('点击下方按钮生成投标文件')")
print()
print("        if st.button('🚀 生成投标文件', type='primary', use_container_width=True):")
print("            # 【问题】这里获取 show_cert_images 的值")
print("            # 【问题】但由于页面可能重新渲染，值可能已经不是用户勾选的值了")
print("            # ...")
print("```")
print()

print("=" * 60)
print("【修复后的代码】（当前版本）：")
print()
print("```python")
print("# 步骤4：生成文件")
print("if current_step >= 3:")
print("    st.markdown('---')")
print("    # 【修复】不设置 value，让 Streamlit 自动管理状态")
print("    show_cert_images = st.checkbox('显示证书图片', key='show_cert_images_final',")
print("                                            ^^^^^^^^^^^^^^^^^^^^^^")
print("    help='选中后，证书 PDF 会转换为图片...')")
print()
print("    # 【调试】在按钮点击时，获取并显示 checkbox 的值")
print("    with st.expander('📝 步骤4：生成投标文件', expanded=(current_step == 3)):")
print("        st.info('点击下方按钮生成投标文件')")
print()
print("        if st.button('🚀 生成投标文件', type='primary', use_container_width=True):")
print("            # 【调试】获取 checkbox 的值")
print("            show_cert_images_value = st.session_state.get('show_cert_images_final', False)")
print("            log_step('show_cert_images 值', {'show_cert_images_final': show_cert_images_value})")
print("            ")
print("            if st.session_state.debug_mode:")
print("                st.info(f'🔍 调试信息：show_cert_images_final = {show_cert_images_value}')")
print("```")
print()

print("=" * 60)
print("【可能的根本原因】：")
print("=" * 60)
print()

print("原因1：expander 嵌套问题")
print("- checkbox 在 expander 外面")
print("- 但生成文件按钮在 expander 里面")
print("- 点击按钮时，可能触发了某些状态变化")
print()

print("原因2：session state 清除问题")
print("- 在某些情况下，session state 可能被意外清除")
print("- 导致 checkbox 的值丢失")
print()

print("原因3：缓存问题")
print("- Streamlit 的 @st.cache_resource 装饰器可能导致状态不一致")
print("- generator 实例可能缓存了旧状态")
print()

print("=" * 60)
print("【建议的解决方案】：")
print("=" * 60)
print()

print("方案1：将 checkbox 移到按钮旁边")
print("- 在 expander 里面，按钮旁边添加 checkbox")
print("- 这样 checkbox 和按钮在同一个上下文中")
print()

print("方案2：使用 st.session_state 显式保存")
print("- 在 checkbox 状态变化时，保存到另一个 key")
print("- 生成文件时，从那个 key 读取")
print()

print("方案3：禁用缓存")
print("- 移除 @st.cache_resource 装饰器")
print("- 每次都创建新的 generator 实例")
print()

print("=" * 60)
print("【临时解决方案】：")
print("=" * 60)
print()

print("现在做的修复：")
print("1. 移除了 checkbox 的 value=False")
print("2. 添加了调试信息，显示 checkbox 的值")
print("3. 确认参数传递链正确")
print()

print("需要用户做的：")
print("1. 重启应用（重要！）")
print("2. 开启调试模式")
print("3. 勾选'显示证书图片'")
print("4. 点击'生成投标文件'")
print("5. 查看调试信息中的 show_cert_images 值")
print("6. 如果是 False，说明没有勾选")
print("7. 如果是 True，但文件中没有图片，说明有其他问题")
print()

print("=" * 60)
